main_app/api/urls.py
from django.urls import path 
from .views import (
    SongListAPI, 
    AlbumAPI,
    ArtistListAPI, 
    add_song_to_playlist, 
    remove_song_from_playlist, 
    PlaylistListAPI,
    SingupView)
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('songs/', SongListAPI.as_view(),name='api_songs'),
    
    path('artists/',ArtistListAPI.as_view(),name = 'api_artists'),
    path('artists/<int:artist_id>/albums', AlbumAPI.as_view(),name='api_albums'),
    
    path('playlists/<int:playlist_id>/add-songs/<int:song_id>',add_song_to_playlist,name='api_add_song_to_playlist'),
    path('playlists/<int:playlist_id>/remove-songs/<int:song_id>',remove_song_from_playlist,name='api_remove_song_from_playlist'),
    path('playlists/',PlaylistListAPI.as_view(),name='api_playlist'),
    path('token/',TokenObtainPairView.as_view(),name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('signup/',SingupView.as_view(), name='signup')
]

main_app/urls.py
from django.urls import path
from .views import (
    SongListView,
    SongDetailView, 
    CreateSongView, 
    UpdateSongView, 
    DeleteSongView,
    ArtistListView,
    CreateArtistView,
    DeleteArtistView,
    UpdateArtistView,
    artist_detail_view,
    add_album_to_artist,
    PlayListView,
    CreatePlaylist,
    UpdatePlaylist,
    DeletePlaylistView,
    playlist_detail_view,
    assoc_song,
    dessoc_song,
    home,
    signup
)

urlpatterns = [
    path('', home, name='home'),
    path('accounts/signup',signup,name='signup'),

    path('all-songs/', SongListView.as_view(),name="song_list"),
    path('all-songs/<int:pk>',SongDetailView.as_view(),name='song_detail'),
    path('all-songs/add',CreateSongView.as_view(), name='song_create'),
    path('all-songs/<int:pk>/update',UpdateSongView.as_view(),name='song_update'),
    path('all-songs/<int:pk>/delete',DeleteSongView.as_view(), name="song_delete"),
    
    path('all-artists/',ArtistListView.as_view(),name='artist_list'),
    path('all-artists/add',CreateArtistView.as_view(),name='artist_create'),
    path('all-artists/<int:artist_id>/',artist_detail_view,name='artist_detail'),
    path('all-artists/<int:pk>/update',UpdateArtistView.as_view(),name='artist_update'),
    path('all-artists/<int:pk>/delete',DeleteArtistView.as_view(), name="artist_delete"),
    path('all-artists/<int:artist_id>/add-song',add_album_to_artist,name='add_album_to_artist'),    
    
    path('all-playlists/', PlayListView.as_view(),name='playlist_list'),
    path('all-playlists/add', CreatePlaylist.as_view(),name='playlist_create'),
    path('all-playlists/<int:pk>/update',UpdatePlaylist.as_view(),name='playlist_update'),
    path('all-playlists/<int:pk>/delete',DeletePlaylistView.as_view(),name='playlist_delete'),
    path('all-playlists/<int:playlist_id>/',playlist_detail_view,name='playlist_detail'),
    path('all-playlists/<int:playlist_id>/assoc-song/<int:song_id>',assoc_song,name='assoc_song'),
    path('all-playlists/<int:playlist_id>/dessoc-song/<int:song_id>',dessoc_song,name='dessoc_song')

    ]

song_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/',include('main_app.api.urls'))
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Song(models.Model):
    title = models.CharField(max_length=200)
    artist = models.CharField(max_length=100)
    link = models.URLField()
    date = models.DateField()

    def __str__(self):
        return f"{self.artist} - {self.title}"
    

class Artist(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

LANGUAGE = (
    ('en', 'English'),
    ('ar', 'Arabic'),
    ('tr', 'Turkish'),
    ('fr', 'French'),
    ('es', 'Spanish'),
    ('de', 'German'),
    ('zh', 'Chinese'),
    ('jp', 'Japanese')
)

class Album(models.Model):
    album_title = models.CharField()
    language = models.CharField(
        max_length= 2,
        choices= LANGUAGE,
        default=LANGUAGE[0][0]
    )
    artist = models.ForeignKey(Artist,on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.album_title} - {self.get_language_display()}"

class Playlist(models.Model):
    name = models.CharField(max_length=50)
    songs = models.ManyToManyField(Song)
    
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

main_app/forms.py
from django.forms import ModelForm
from .models import Album

class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = ['album_title','language']

main_app/api/views.py
from rest_framework.views import APIView
from main_app.models import Song, Artist, Album,Playlist
from .serializers import SongSerializer, AlbumSerializer,ArtistSerializer,PlaylistSerializer
from rest_framework.response import Response
from rest_framework import status
from django.shortcuts import get_object_or_404
from rest_framework.decorators import api_view, permission_classes

from rest_framework.permissions import IsAuthenticated, AllowAny

from django.contrib.auth.models import User
from rest_framework_simplejwt.tokens import RefreshToken
from django.contrib.auth.password_validation import validate_password 
from django.core.exceptions import ValidationError

class SingupView(APIView):
    permission_classes = [AllowAny]

    def post(self,request):
        username = request.data.get('username')
        email = request.data.get('email')
        password = request.data.get('password')
        print(password)

        try:
            validate_password(password=password)
        except ValidationError as err:
            return Response({'error': err.messages} ,status=status.HTTP_400_BAD_REQUEST)
        
        # create user 
        user = User.objects.create_user(
            username=username,
            email=email,
            password=password
        )
        # create an access and refresh token 
        # for the user and send this in a response
        tokens = RefreshToken.for_user(user=user)
        return Response (
            { 'refresh':str(tokens), 'access': str(tokens.access_token)},
            status= status.HTTP_201_CREATED
        )

################# Function VIEW  ##################
# many to many relationship with Playlist model and song model
# add song
@api_view(['POST'])
@permission_classes([IsAuthenticated])
def add_song_to_playlist(request,playlist_id,song_id):
    try:
        # GET the playlist by playlist_id 
        playlist = Playlist.objects.get(pk=playlist_id)
        #print(playlist)
        # Get the song by song_id
        song = Song.objects.get(pk=song_id)
        #print(song)
        # add the song to the playlist
        if playlist.songs.filter(id=song_id).exists():
            return Response({'message': 'The the song already exists in the playlist!'})
        else:    
            playlist.songs.add(song)
            return Response({'message':'song was Added!'},status=201)
    except Playlist.DoesNotExist:
        return Response({'error':'the playlist does not exists'},status=404)
    except Song.DoesNotExist:
        return Response({'error':'the song does not exists'},status=404)
    except:
        return Response({'error':'Something went Wrong'},status=status.HTTP_500_INTERNAL_SERVER_ERROR)
# remove song
@api_view(['POST'])
def remove_song_from_playlist(request,playlist_id,song_id):
    try:
        # GET the playlist by playlist_id 
        playlist = Playlist.objects.get(pk=playlist_id)
        print(playlist)
        # Get the song by song_id
        song = Song.objects.get(pk=song_id)
        print(song)
        # remove the song to the playlist if exists
        if playlist.songs.filter(id=song_id).exists():
            playlist.songs.remove(song)
            return Response({'message':'song removed!'},status=status.HTTP_200_OK)
        else: 
            # not exist show message
            return Response({'message': 'The song is in the DB but it is not on the playlist!'})    
    except Playlist.DoesNotExist:
        return Response({'error':'the playlist does not exists'},status=404)
    except Song.DoesNotExist:
        return Response({'error':'the song does not exists'},status=404)
    except:
        return Response({'error':'Something went Wrong'},status=status.HTTP_500_INTERNAL_SERVER_ERROR)

################## CLASS-BASED VIEW  ##################
class SongListAPI(APIView):

    def get(self,request):
        # get all songs from the DB
        songs = Song.objects.all()
        # serializer our songs into JSON
        serializer = SongSerializer(songs,many=True)
        return Response(serializer.data)

    def post(self, request):
        # De-serialize our data
        serializer = SongSerializer(data=request.data)
        # if valid return response of 201 created
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        # if anything happens, erorr then 400 bad request
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    
    # I created this so I can see all the artists 
class ArtistListAPI(APIView):
    def get(self,request):
        # get all songs from the DB
        artists = Artist.objects.all()
        # serializer our songs into JSON
        serializer = ArtistSerializer(artists,many=True)
        return Response(serializer.data)

    def post(self, request):
        # De-serialize our data
        serializer = ArtistSerializer(data=request.data)
        # if valid return response of 201 created
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        # if anything happens, erorr then 400 bad request
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)

class AlbumAPI(APIView):
    def get(self, request, artist_id):
        artist = get_object_or_404(Artist,pk=artist_id)
        albums = Album.objects.filter(artist_id = artist.pk)
        serializer = AlbumSerializer(albums,many=True)
        return Response(serializer.data)

    def post(self,request,artist_id):
        #  the artist id will be passed into get_object_or_404 function, 
        # it will return the artist obj if exists, or it will raise a 404
        # if it doesnt exist 
        artist = get_object_or_404(Artist,pk=artist_id)
        data = request.data.copy() # make a copy
        data['artist'] = artist.id # add the artist to the ablum
        
        serializer = AlbumSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        return Response(serializer.errors,status=400)

class PlaylistListAPI(APIView):
    permission_classes = [IsAuthenticated]

    def get(self,request):
        # get all songs from the DB
        playlist = Playlist.objects.filter(user=request.user)
        # serializer our songs into JSON
        serializer = PlaylistSerializer(playlist,many=True)
        return Response(serializer.data)

    def post(self, request):
        # De-serialize our data
        serializer = PlaylistSerializer(data=request.data)
        # if valid return response of 201 created
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        # if anything happens, erorr then 400 bad request
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    

main_app/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView, DetailView, CreateView
from .models import Song, Artist, Album, Playlist
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, DeleteView
from .forms import AlbumForm

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

# Create your views here.
# signup
def signup(request):
    # prevent user from seeing signup form
    if request.user.is_authenticated:
        return redirect('home')
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('home')
        
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

# home page
def home(request):
    return render(request, 'home.html')

class SongListView(LoginRequiredMixin,ListView):
    model = Song
    template_name = 'song_list.html'
    context_object_name = 'songs'

class SongDetailView(LoginRequiredMixin,DetailView):
    model = Song
    template_name = 'song_detail.html'
    context_object_name = 'song'

# make sure that the user should be an is_superuser in specific views
# I searched about it :https://stackoverflow.com/questions/51284583/authentication-for-class-based-views-in-django
# I will use AdminStaffRequiredMixin to check if it's admin logged-in
class AdminStaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    
    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

class CreateSongView(AdminStaffRequiredMixin,CreateView):
    model = Song
    fields = ['title', 'artist', 'date', 'link']
    template_name = 'song_form.html'
    success_url = reverse_lazy('song_list')

class UpdateSongView(AdminStaffRequiredMixin,UpdateView):
    model = Song
    fields = ['title', 'artist', 'date', 'link']
    template_name = 'song_form.html'
    success_url = reverse_lazy('song_list')

class DeleteSongView(AdminStaffRequiredMixin,DeleteView):
    model = Song
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('song_list')

    # Artist model 
class ArtistListView(LoginRequiredMixin, ListView):
    model = Artist
    template_name = 'artist_list.html'
    context_object_name = 'artists'

@login_required
def artist_detail_view(request,artist_id):
    artist = Artist.objects.get(id = artist_id)
    album_form = AlbumForm()

    return render(request,'artist_detail.html',{ 
        'artist': artist, 
        'album_form': album_form
    })
@login_required
def add_album_to_artist(request,artist_id):
    form = AlbumForm(request.POST)
    if form.is_valid():
        new_song = form.save(commit=False)
        # add song id to db
        new_song.artist_id = artist_id
        new_song.save()# save to DB
    # redirect the uset to same page
    return redirect('artist_detail',artist_id = artist_id)

class CreateArtistView(AdminStaffRequiredMixin,CreateView):
    model = Artist
    fields = ['name']
    template_name = 'artist_form.html'
    success_url = reverse_lazy('artist_list')    

class UpdateArtistView(AdminStaffRequiredMixin,UpdateView):
    model = Artist
    fields = ['name']
    template_name = 'artist_form.html'
    success_url = reverse_lazy('artist_list')

class DeleteArtistView(AdminStaffRequiredMixin,DeleteView):
    model = Artist
    template_name = 'confirm_delete_artist.html'
    success_url = reverse_lazy('artist_list')


#############    playlist     #############
# adding a playlist, each user will have many playlist 
## each user can create a playlist and add songs to it
## I will use LoginRequiredMixin which is for class based view
class PlayListView(LoginRequiredMixin,ListView):
    model = Playlist
    template_name = 'playlist_list.html'
    context_object_name = 'playlist' 
    def get_queryset(self):
        return Playlist.objects.filter(user = self.request.user)

class CreatePlaylist(LoginRequiredMixin,CreateView):
    model = Playlist
    fields = ['name']
    template_name = 'playlist_form.html'
    success_url = reverse_lazy('playlist_list')    
    
    def form_valid(self, form):
        # Assign the logged in user  to the form instance
        form.instance.user = self.request.user 
        return super().form_valid(form)
    
class UpdatePlaylist(LoginRequiredMixin,UpdateView):
    model = Playlist
    fields = ['name']
    template_name = 'playlist_form.html'
    success_url = reverse_lazy('playlist_list') 

class DeletePlaylistView(LoginRequiredMixin,DeleteView):
    model = Playlist
    template_name = 'confirm_delete_playlist.html'
    success_url = reverse_lazy('playlist_list') 

@login_required
def playlist_detail_view(request,playlist_id):
    playlist = Playlist.objects.get(id=playlist_id)
    songs_playlist_does_not_have = Song.objects.exclude(id__in = playlist.songs.all().values_list('id'))
    return render (request, 'playlist_detail.html',{
        'playlist': playlist,
        'songs_playlist_does_not_have': songs_playlist_does_not_have
    })

@login_required
def assoc_song(request,playlist_id,song_id):
    # add a song to playlist
    Playlist.objects.get(id = playlist_id).songs.add(song_id)
    return redirect('playlist_detail',playlist_id = playlist_id)
@login_required
def dessoc_song(request,playlist_id,song_id):
    # delete a specific song from playlist
    Playlist.objects.get(id=playlist_id).songs.remove(song_id)
    return redirect('playlist_detail',playlist_id = playlist_id)

main_app/templates/artist_detail.html
{% extends 'base.html'%}

{% block content%}
<h1>Artist:</h1>
<h2>{{ artist.name }}</h2>
<!-- Only admin can add artist to program: 
i found this way when I searched: https://stackoverflow.com/questions/69428225/allow-page-access-only-for-admin-user-django -->
{% if user.is_superuser %}
<a href="{% url 'artist_update' artist.pk%}">Edit</a>
<a href="{% url 'artist_delete' artist.pk%}">Delete</a>
{%endif%}
<h2>Album:</h2>
<!-- Only admin can add albums to artist: 
i found this way when I searched: https://stackoverflow.com/questions/69428225/allow-page-access-only-for-admin-user-django -->
{% if user.is_superuser %}
<form action="{% url 'add_album_to_artist' artist.id%}" method="post">
    {% csrf_token %}
    {{album_form.as_p}}
    <input type="submit" value="Add Album">
</form>
{%endif%}
<table class="striped">
    <thead>
        <tr>
            <th>Album</th>
            <th>Language</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            {% for album in artist.album_set.all %}
            <td>{{album.album_title}}</td>
            <td>{{album.get_language_display}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<script>
    const selectElement = document.querySelector('#id_language')
    M.FormSelect.init(selectElement)
</script>
{% endblock%}

main_app/templates/artist_form.html
{% extends 'base.html'%}

{% block content%}
<h1>{% if object %} Edit {% else %} Create {% endif %} Artist </h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form>
{% endblock %}

main_app/templates/artist_list.html
{% extends 'base.html'%}

{% block content%}
<h1>
    All Artist:
</h1>

<ul>
    {%for artist in artists%}
    <li>
        <a href="{% url 'artist_detail' artist.pk %}">{{artist.name}}</a>
    </li>
    {% empty%}
    <h2>There are no artist</h2>
    {% endfor %}
</ul>
<!-- Only admin can add artists to program: 
i found this way when I searched: https://stackoverflow.com/questions/69428225/allow-page-access-only-for-admin-user-django -->
{% if user.is_superuser %}
<a href="{% url 'artist_create' %}">Add Artist + </a>
{%endif%}
{% endblock%}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Song Collecotr</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/style.css'%}">
    <!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <nav>
        <a href="{%url 'home' %}"> Home </a>
        {% if user.is_authenticated %}
            <a href="{% url 'song_list'%}">  All Songs  </a>
            <a href="{% url 'artist_list'%}">  Artists  </a>
            <a href="{% url 'playlist_list'%}">  All playlist  </a>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log Out</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Log In</a>
            <a href="{% url 'signup' %}">Sign Up</a>
        {%endif%}
</nav>
    <main>
        {% block content %}
        <!-- this where the indiviual pages will be rendered -->
        {% endblock %}
    </main>
</body>
</html>

main_app/templates/confirm_delete.html
{% extends 'base.html'%}

{% block content%}
<h2>Are You Sure You Want To Delete {{object.title}} ?</h2>
<form method="post">
    {%csrf_token%}
    <button type="submit"> Confirm</button>
</form>

<a href="{% url 'song_detail' object.pk%}"> Cancel</a>
{% endblock%}

main_app/templates/confirm_delete_artist.html
{% extends 'base.html'%}

{% block content%}
<h2>Are You Sure You Want To Delete {{object.name}} ?</h2>
<form method="post">
    {%csrf_token%}
    <button type="submit"> Confirm</button>
</form>

<a href="{% url 'artist_detail' object.pk%}"> Cancel</a>
{% endblock%}

main_app/templates/confirm_delete_playlist.html
{% extends 'base.html'%}

{% block content%}
<h1> Are You sure you want to delete {{ object.name }} ?</h1>
<form method="post">
    {% csrf_token %}
    <button type="submit"> Confirm </button>
</form>

<a href="{% url 'playlist_detail' object.pk%}"> Cancel</a>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html'%}

{% block content%}
<h1>Welcome To Song Collector APP 🎵</h1>

{%endblock%}

main_app/templates/playlist_detail.html
{% extends 'base.html'%}

{% block content%}

<h1>{{playlist.name}}🎶</h1>
<a href="{% url 'playlist_update' playlist.pk%}"> Edit</a>
<a href="{% url 'playlist_delete' playlist.pk%}"> Delete</a>
{% if playlist.songs.count %}
    <h4>Songs:</h4>
    {% for song in playlist.songs.all%}
        <p> &nbsp; <b>{{song.title}}</b> link to play
            <a href="{{song.link}}">{{song.link}}</a></p>
            <form method="post" action="{% url 'dessoc_song' playlist.id song.id%}">
                {%csrf_token%}
                <button type="submit">Remove</button>
            </form>
    {%endfor%}
{% else%}
    <h5> &nbsp; No songs added to playlist ! </h5>
{% endif%}

{% if songs_playlist_does_not_have.count %}
    <h4>Available Songs:</h4>
    {% for song in songs_playlist_does_not_have %}
            <p>&nbsp;{{song.title}}</p>
            <form method="post"action="{% url 'assoc_song' playlist.id song.id%}">
                {%csrf_token%}
                <button type="submit" > Add Song</button>  
            </form>
    {% endfor %}
    {% else %}
            <h5>No Available Songs</h5>
    {% endif %}

{% endblock%}

main_app/templates/playlist_form.html
{% extends 'base.html'%}

{% block content%}
<h1>{% if object %} Edit {% else %} Create {% endif %} Playlist </h1>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form>

{% endblock %}

main_app/templates/playlist_list.html
{% extends 'base.html'%}

{% block content%}
<h1>All Playlist</h1>
<ul>
        {% for playlist in playlist %}
        <li>
            <a href="{% url 'playlist_detail' playlist.id %}"><h4>{{playlist.name}} 🎧</h4></a>

        </li>
        {% empty%}
        <h2>There are no playlist 🎶 </h2>
        {% endfor %}
    </ul>
    <a href="{% url 'playlist_create' %}">Add a playlist</a>

{% endblock%}

main_app/templates/song_detail.html
{% extends 'base.html'%}

{% block content%}
<h1>Song Details 🎵</h1>
<h2>{{song.title}}</h2>
<p>Artist: {{song.artist}} </p>
<p>Release on: {{song.date}}</p>
<p>link: <a href="{{song.link}}"> {{song.link}}</a></p>

<!-- Only admin can edit or delete songs : 
i found this way when I searched: https://stackoverflow.com/questions/69428225/allow-page-access-only-for-admin-user-django -->
{% if user.is_superuser %}
<a href="{% url 'song_update' song.pk%}">Edit</a>
<a href="{% url 'song_delete' song.pk%}">Delete</a>
{%endif%}
{% endblock%}

main_app/templates/song_form.html
{% extends 'base.html'%}

{% block content%}
<h1>{% if object %} Edit {% else %} Add {% endif %} Song</h1>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> Save </button>

</form>

<script>
    const dateElement = document.querySelector('#id_date')
    M.Datepicker.init(dateElement, {
        // ISO Date
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })
</script>
{% endblock%}

main_app/templates/song_list.html
{% extends 'base.html'%}

{% block content%}
<h1>Songs List🎶:</h1>
<ul style="list-style-type: none; ">
    {% for song in songs %}
        <li>
            <a href="{%url 'song_detail' song.pk%}">
                <h3>{{song.title}}🎵 </h3>
            </a>
        </li>
    {% empty%}
    <h2>There are no songs🎵 </h2>
    {% endfor %}
</ul>
<!-- Only admin can add songs to program: 
i found this way when I searched: https://stackoverflow.com/questions/69428225/allow-page-access-only-for-admin-user-django -->
{% if user.is_superuser %}
<a href="{% url 'song_create' %}">Add Song + </a>
{%endif%}

{% endblock%}